FROM python:3.7

RUN pip install torch
RUN pip install torchvision
RUN pip install flwr
RUN pip install matplotlib
RUN pip install numpy
RUN pip install tqdm

COPY . /app
WORKDIR /app

CMD ["python", "client.py"]
