version: "3"

services:
  
  attacker:
    image: swat:latest
    command: bash -c "python2 attacker.py"
    networks: 
      SWAT:
    volumes:
      - ../:/app

  plc1:
    image: swat:latest
    command: bash -c "python2 plc1.py"
    networks: 
      SWAT:
    volumes:
      - ../:/app

  plc2:
    image: swat:latest
    command: bash -c "python2 plc2.py"
    networks: 
      SWAT:
    volumes:
      - ../:/app
  
  plc3:
    image: swat:latest
    command: bash -c "python2 plc3.py"
    networks: 
      SWAT:
    volumes:
      - ../:/app

# SWaT network
networks:
  SWAT:
    ipam:
      driver: default
      config:
        - subnet: "113.10.0.0/16"
