version: "3"
services:
  server:
    image: flwr-server:latest
    networks: 
      learning:
        ipv4_address: "172.18.0.2"
    volumes:
      - ../:/app
    healthcheck:
        test: ["CMD", "echo", "Alive"]
        interval: 5s
        timeout: 10s
        retries: 5
  client:
    image: flwr-client:latest
    networks: 
      learning:
    deploy:
      mode: replicated
      replicas: 2
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ../:/app
    depends_on:
      server:
        condition: service_healthy
    links:
      - server
networks:
  learning:
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/16"