version: "3"

services:
  
  # CPS network components

  ###
  # TO RUN: docker-compose up -d > [inside each plc] python2 plc[n].py (twice)
  ###

  plc1:
    image: redclouud/trist:latest
    command: bash -c "tshark -i eth0 -w /home/plc1.pcap & sleep 999999" # python2 plc1.py" #  " # test Ether/IP communication
    networks: 
      TRIST:
        ipv4_address: 192.168.1.10
    privileged: true
    volumes:
      - ../../../:/minicps
      # - ../pcap:/home # tshark does not currently have permission to write to volumes
  
  plc2:
    image: redclouud/trist:latest
    command: bash -c "tshark -i eth0 -w /home/plc2.pcap & sleep 999999" # python2 plc2.py" #  " # test Ether/IP communication 
    # enip_server --print SCADA@22/1/1=INT[1000] TEXT@22/1/2=SSTRING[100] FLOAT@22/1/3=REAL
    # enip_server --print FIT201:2=REAL MV201:2@22/1/1=INT[10]
    networks: 
      TRIST:
        ipv4_address: 192.168.1.20
    privileged: true
    volumes:
      - ../../../:/minicps
  
  plc3:
    image: redclouud/trist:latest
    command: bash -c "tshark -i eth0 -w /home/plc3.pcap & sleep 999999"
    networks: 
      TRIST:
        ipv4_address: 192.168.1.30
    privileged: true
    volumes:
      - ../../../:/minicps
  
  physical_process:
    image: redclouud/trist:latest
    command: bash -c "python2 physical_process.py"
    volumes:
      - ../../../:/minicps

  # # Attacker
  # slowloris:
  #   image: aminvakil/slowloris:latest
  #   command: 192.168.1.10 -p 44818 # targeting Ethernet/IP port on PLC1
  #   networks:
  #     TRIST:
  #       ipv4_address: 192.168.1.77 # attacker is on same network as PLCs

  # Data visualisation
  # elk:
  #   image: sebp/elk
  #   port:
  #     - "5601:5601"
  #     - "9200:9200"
  #     - "5044:5044"
  #   networks:
  #     TRIST:
  #   volumes: 
  #     - suricata:/var/log/suricata
  #     - elk:/all/required/directories


# Network for container communication
networks:
  TRIST:
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.0/24"

# volumes:
#   suricata:
#   tshark:
#   elk:
